apiVersion: v1
kind: Service
metadata:
  name: todo-db
  labels:
    name: todo-db
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5432
    targetPort: 5432
  selector:
    name: todo-db
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  todo-db-deploy
  labels:
    name:  todo-db
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  todo-db
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - image:  hackfesttodocontainerregistry.azurecr.io/hackfest/todo-db:v1
        name:  todo-db-cntnr
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        ports:
        - containerPort:  5432
          name:  todo-db
        volumeMounts:
        - mountPath: /data
          name: data
        imagePullPolicy: Always
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
      